version: "3.7"
services:
 api:
  build:
   context: .
   target: build
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - 3000:3000
  command: npm run dev

 mysql:
  image: mysql:8.3.0
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_ROOT_HOST: "%"
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  volumes:
    - mysql:/var/lib/mysql

volumes:
  mysql: